name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: "Features"
    labels:
      - "feature"
  - title: "Bug Fixes"
    labels:
      - "bug"
  - title: "Maintenance"
    labels:
      - "maintenance"
  - title: "Documentation"
    labels:
      - "documentation"

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"

template: |
  ## What's new in v$NEXT_PATCH_VERSION

  ### Release Date
  _Released on ${{ env.RELEASE_DATE }}_

  $CHANGES

  ## Contributors
  Thank you to all the contributors who made this release possible:
  $CONTRIBUTORS

  ## Links
  - [Compare changes](https://github.com/${{ env.OWNER }}/${{ env.REPO }}/compare/${{ env.PREVIOUS_TAG }}...${{ env.NEW_TAG }})
  - [Full changelog](https://github.com/${{ env.OWNER }}/${{ env.REPO }}/releases/tag/${{ env.NEW_TAG }})

  <!-- Optional: Include other metadata if necessary -->
